kind: pipeline
name: default

steps:
  - name: test
    image: python:3.8
    commands:
      - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pip install pytest -i https://pypi.tuna.tsinghua.edu.cn/simple
      - pytest -v tests
