[tool.poetry]
name = "najia"
version = "0.1.0"
description = ""
authors = ["bopo <ibopo@126.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.2.3"
click = "^8.1.3"
jinja2 = "^3.1.2"
sxtwl = "^2.0.6"
tzlocal = "^4.3"


[[tool.poetry.source]]
name = "mirrors"
url = "https://mirrors.ustc.edu.cn/pypi/web/simple"
default = false
secondary = false


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
